version: "3"
services:
  server:
    container_name: server
    build: .
    ports: 
      - "80:5000"
    depends_on:
      - db
    volumes:
      - .:/server
    env_file: 
      - .env
  db:
    image: postgres:13
    container_name: db
    ports:
      - 2345:5432
    env_file: 
      - .env
    restart: always
    volumes: 
      - postgres:/var/lib/postgresql/data
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 80:80
volumes:
  postgres: