version: "3"
services:
  server:
    container_name: server
    build: ./server
    ports:
      - "8080:443"
    depends_on:
      - db
    volumes:
      - ./server:/server
      - ./server/certificados:/server/certificados
    env_file:
      - ./server/.env
  db:
    image: postgres:13
    container_name: db
    ports:
      - 2345:5432
    env_file:
      - ./server/.env
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - server
volumes:
  postgres:
